### ISSUE TITLE
Use api key from env variable

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [Dhi13man/open_route_service#9]
One option to use your api key for tests without exposing it is implementing it as an environment variable and read it from there. Here is an example with github workflows:
https://dev.to/jonathangomz/github-actions-for-dart-package-with-environment-variables-5heb

**Comment by Dhi13man** [comment]
Hey. Just got it figured out and set up. Thank you so much for the information. I am still a beginner relatively, so I had no idea. xD

(I think my free token quota ran out which is why the build is failing. Should be passing again by tomorrow)

**Edit:** Was a scope issue with the way I was updating API key for tests in Github Actions. The key was never being set. Fixed now and building.  :)
